//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.AwayFixtures = new HashSet<Fixture>();
            this.HomeFixtures = new HashSet<Fixture>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationSource { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string MaintenanceSource { get; set; }
        public int GroupId { get; set; }
        public string Name { get; set; }
        public string Flag { get; set; }
        public bool Eliminated { get; set; }
        public Nullable<int> Played { get; set; }
        public Nullable<int> Won { get; set; }
        public Nullable<int> Drawn { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Scored { get; set; }
        public Nullable<int> Conceded { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual ICollection<Fixture> AwayFixtures { get; set; }
        public virtual ICollection<Fixture> HomeFixtures { get; set; }
        public virtual Group Group { get; set; }
    }
}
