//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016ResultGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixture
    {
        public Fixture()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationSource { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string MaintenanceSource { get; set; }
        public int HomeTeamId { get; set; }
        public int AwayTeamId { get; set; }
        public System.DateTime Date { get; set; }
        public int VenueId { get; set; }
    
        public virtual Venue Venue { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual Team AwayTeam { get; set; }
        public virtual Team HomeTeam { get; set; }
    }
}
