//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Euro2016ResultGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationSource { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public string MaintenanceSource { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Team> Teams { get; set; }
    }
}
